name: kc_kape_mo
description: Enhanced coffee app with advanced features
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  provider: ^6.1.1
  intl: ^0.18.1
  cloud_firestore: ^5.0.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.6.0
  http: ^1.2.1
  url_launcher: ^6.2.5
  fluttertoast: ^8.2.1
  webview_flutter: ^4.4.2
  confetti: ^0.7.0
  fl_chart: ^0.64.0
  animated_flip_counter: ^0.2.6

flutter:
  uses-material-design: true